### ISSUE TITLE
not working on hosting server

### ISSUE THREAD

**Issue by bartoszzajac** [acelaya/ZF-AcMailer#139]
Any ideas why mails aren't sent from online server when everything works on my local server? I use smtp and gmail.

**Comment by acelaya** [comment]
It's hard to say without seeng any error. Maybe gmail blocks that host?
Could you provide the exception trace?

**Comment by bartoszzajac** [comment]
It's problem with my configuration I suppose. I made email on target domain and that is even better than sending from gmail (I use this for contact form). I will back to problem with gmail if it will not work for me in the future but I think this is not ACMailer issue.

**Comment by bartoszzajac** [comment]
It is gmail who blocked it. It is necessarily to login to gmail and accept login from unknown source.

**Comment by acelaya** [comment]
I'm closing this then
