### ISSUE TITLE
Tests are not passing with Zend EventManager 3

### ISSUE THREAD

**Issue by tdutrion** [acelaya/ZF-AcMailer#141]
When writing some evolutions, I encountered a problem with the test suite. Details can be found on [travisci](https://travis-ci.org/acelaya/ZF-AcMailer/jobs/186290412).

```
There was 1 error:
1) AcMailerTest\Service\MailServiceAbstractFactoryTest::testListeners
ReflectionException: Method getListenersByEventName does not exist
/home/travis/build/acelaya/ZF-AcMailer/test/Service/MailServiceAbstractFactoryTest.php:359
```

According to the migration guide, there may be no new ways to do this feature: [Zend EventManager v3 - Migration - Removed](https://github.com/zendframework/zend-eventmanager/blob/master/doc/book/migration/removed.md#eventmanagerinterfacegetevents-and-getlisteners)

Solution might involve a reflection object, and making the events attribute public so we can count the number of listeners under the key we want. I would advise against it as it means testing against the actual `EventManager` class and not the `EventManagerInterface`.

```
$em = $mailService->getEventManager();
$refObject = new \ReflectionObject($em);
$method = $refObject->getMethod('getListenersByEventName');
$method->setAccessible(true);

$this->assertCount(3, $method->invoke($em, MailEvent::EVENT_MAIL_PRE_SEND));
```

```
$em = $mailService->getEventManager();
$refObject = new \ReflectionObject($em);
$attr = $refObject->getProperty('events');
$attr->setAccessible(true);
$this->assertCount(3, $attr->getValue($em)[MailEvent::EVENT_MAIL_PRE_SEND][1][0]);
```

Another solution I can think of is to trigger the event and see the result. I am definitely not sure what kind of result we can expect and how to count how many listeners we went through, I don't know the event manager enough here...

**Comment by acelaya** [comment]
I think I had to deal with this some time ago in another project.
I'll try to fix it.

**Comment by acelaya** [comment]
This is duplicated #142, so I'm closing this.
