### ISSUE TITLE
Events with ZF3 doesn't work

### ISSUE THREAD

**Issue by Syberon** [acelaya/ZF-AcMailer#142]
Hi.

I try to use the events triggered by AcMailer by using a Listener class that extends AbstractMailListener. This class instantiates via factory and attaches to AcMailer in config (mail_listeners). There is no errors, but events doesn't works. I found a solution for this problem, in file /src/Service/MailService.php (method getEventManager):

source line:
$this->setEventManager(new EventManager());

modified:
$this->setEventManager(new EventManager(new SharedEventManager()));

ZF3 requires that the shared event manager be injected at instantiation, instead of via a setter. In current version of AcMailer event listeners attached in service factory and event manager resets after factory return service object.

**Comment by acelaya** [comment]
This has probably something to do with #141.
I'll try to fix it, but any PR is welcome ;)

**Comment by acelaya** [comment]
Already fixed. It will be immediately available in v6.3.1
