### ISSUE TITLE
Make sure email templates are rendered before the PRE_SEND event is triggered

### ISSUE THREAD

**Issue by barannd** [acelaya/ZF-AcMailer#187]
In past versions it was possible to modify the email body of a template rendered email in the MailEvent::EVENT_MAIL_PRE_SEND event. Now the event gets triggered before the rendering process. Is it possible to change that?

**Comment by acelaya** [comment]
If that's the case, that's an unintended regression and I would fix it.
Let me make some tests.

**Comment by acelaya** [comment]
I've just released v7.0.3 which fixes this.

Now, when an email is composed from a template, you can access the already rendered template in a PRE_SEND listener by calling `$e->getEmail()->getBody()`

**Comment by barannd** [comment]
Thank you very much for the quick fix!

**Comment by acelaya** [comment]
You are welcome :)
