### ISSUE TITLE
Allow adding custom headers to emails

### ISSUE THREAD

**Issue by barannd** [acelaya/ZF-AcMailer#201]
Is there a way to add a custom header to the email being sent?

**Comment by barannd** [comment]
i would appreciate it, if you could add it. I really don't know how it works to create a pull request with changes in the repository. But I will take a closer look at this in the near future.

Thanks in advance!

**Comment by acelaya** [comment]
Ok, I'll implement it, but I can't warranty it's going to be soon

**Comment by barannd** [comment]
Yeahh sure, thank you very much!

**Comment by acelaya** [comment]
Hey!

Sorry for the delay, but I have just released version [7.3.0](https://github.com/acelaya/ZF-AcMailer/releases/tag/v7.3.0), which includes this feature.

Let me know if you find any issue.
