### ISSUE TITLE
Set the real name in the To: header

### ISSUE THREAD

**Issue by jonathanmaron** [acelaya/ZF-AcMailer#206]
Hello

I am currently in the process of updating ZF-AcMailer v6.4 to v7.3. I appreciate the guide that you have written. Thank you.

In 6.4, it was possible to set the real name of the "to" address, so that the "To:" header was, for example:

    Joe Doe <joe@doe.org>

In 7.3, as far as I can see, only the email address can be set, for example:

    joe@doe.org

Did I miss something, or has this feature been removed?

ZF-AcMailer is a really great component. Thank you for your hard work.

With kindest regards

Jonathan Maron

**Comment by acelaya** [comment]
Hey!

Thanks for the kind word.

Yes, you can still do that. The `to` param is now an array. If you use a key-value approach, you will get what you want:

* `$mailService->send(..., ['to' => ['joe@doe.org']])` will result in the header `To: joe@doe.org`
* `$mailService->send(..., ['to' => ['joe@doe.org' => 'John Doe']])` will result in the header `To: Joe Doe <joe@doe.org>`

**Comment by jonathanmaron** [comment]
Hello Alejandro

I appreciate your response. 

The problem I was facing is now solved. The "To:" header is now with real name. Thank you!

Jonathan Maron
