### ISSUE TITLE
Write permissions required when probably not needed

### ISSUE THREAD

**Issue by cbichis** [acelaya/ZF-AcMailer#218]
FilePathAttachmentParser line 38:

`$part = new Mime\Part(\fopen($attachment, 'r+b'));`

Any reason for this ? I guess read only permissions would be more than enough.

**Comment by acelaya** [comment]
Maybe you are right, but I would need to make some tests though.

Is it causing some issue?

**Comment by acelaya** [comment]
Yep, I think it makes sense. I'll treat this as a bug and try to change it.

**Comment by cbichis** [comment]
Great, have a nice evening!

**Comment by acelaya** [comment]
I have just verified that permission is not actually needed, and it fails if the user does not have write permissions on the file.

v7.3.2 will be available soon.

**Comment by acelaya** [comment]
v7.3.2 is already available including this fix.

**Comment by cbichis** [comment]
Great, thanls.
