### ISSUE TITLE
How can dynamically set up the transport on AcMailer7?

### ISSUE THREAD

**Issue by x-fran** [acelaya/ZF-AcMailer#226]
There is no setter or any other way in MailService to dynamically set up the transport.
At least I can't find one.

Thanks in advance.

**Comment by acelaya** [comment]
Dynamically setting dependencies on a service is usually not the best option, but there are other possible approaches.

Can you give me some more information on how did you use to do it? I think there should be a way to adapt it to v7

**Comment by x-fran** [comment]
I have an API, each API user has his clients. I need to be able to send emails using the user's SMTP configuration to his clients. Some of the users are using Gmail, others Outlook, others Amazon. This is the reason I need to set up the transport dynamically. All this is part of a B2B EDI.
I hope I explain myself.
Thank you.

**Comment by acelaya** [comment]
Ok, I got it.

I have something in mind. I will explain later with an example.

**Comment by acelaya** [comment]
Let's do something else.

There are a couple of hacky ways to solve this, but it's actually way easier to solve from AcMailer's side, so instead of making you maintain some extra code, I'm going to release v7.4 which will support this.

I should be able to publish it today if nothing else comes up.

**Comment by x-fran** [comment]
Great!! Thank you.

**Comment by acelaya** [comment]
Hello @x-fran 

I have just released [v7.4.0], which adds a new service which allows dynamically creating MailServices at runtime.

You can see the docs [here](http://acelaya.github.io/ZF-AcMailer/#/configuring-services?id=dynamic-runtime-configuration)

Let me know if you find something which is not working as expected.

**Comment by x-fran** [comment]
Once the module is enabled I get the following notice:

Notice: Undefined offset: 1 in /xxxxx-edi/api/api/vendor/acelaya/zf2-acmailer/src/Service/Factory/MailServiceAbstractFactory.php on line 61

Notice: Undefined offset: 2 in /xxxxx-edi/api/api/vendor/acelaya/zf2-acmailer/src/Service/Factory/MailServiceAbstractFactory.php on line 61

**Comment by acelaya** [comment]
I did a small change that could be producing that (easy to fix, though), but the problem here is that it seems you are trying to create a mail service without the proper naming formula, which will result in an exception.

You should always use something like `acmailer.mailservice.XXX`.

Could this be the issue?

**Comment by acelaya** [comment]
I have just realized that the method throwing those notices is probably being called when trying to create other services. I does not need ot be directly related with MailServices.

I have just released v7.4.1 fixing it.

**Comment by x-fran** [comment]
I'm using "acmailer.mailservice.default'" and the default configuration for SMTP in mail.global.php
The email works correctly. This is the configuration I have in my controller and I've been tested 

```
[[`$mailService = $this->mailServiceBuilder->build('acmailer.mailservice.default', [
            'transport_options' => [
                'host' => 'smtp.gmail.com',
                'port' => 587,
                'connection_class' => 'login',
                'connection_config' => [
                    'username' => 'support@domain.ie',
                    'password' => 'xxxxx',
                    'ssl' => 'tls',
                ],
            ],
        ]);`]]
```

All I have left is a test with the template. Was just that notice, which is fixed.
Thank you again for your support. Great module, great job.

**Comment by acelaya** [comment]
I'm glad everything was sorted out :)
