### ISSUE TITLE
Unable to render template

### ISSUE THREAD

**Issue by x-fran** [acelaya/ZF-AcMailer#233]
I'm getting the following error
```
Zend\View\Renderer\PhpRenderer::render: Unable to render template "ModuleName/view/mail/template"; resolver could not resolve to a file
```
```
Zend\View\Renderer\PhpRenderer::render: Unable to render template "./module/ModuleName/view/mail/template"; resolver could not resolve to a file
```
Already tried using the full path to file. I'm getting the same error.

Any ideas?

Thank you in advance.

**Comment by x-fran** [comment]
I forgot to mention, the first option is_file returns false, the second one returns true, third one full path also returns true.

**Comment by acelaya** [comment]
Was the config working with v6 and stopped working with v7?

**Comment by x-fran** [comment]
Never tried v6. I used v5 long long time ago and the template worked.

**Comment by acelaya** [comment]
Ok.

Then I would recommend checking the view_renderer config first, since template resolution is done by the standard view renderer.

**Comment by x-fran** [comment]
Do you mean view_manager?

**Comment by acelaya** [comment]
Yeah, sorry, that's what I meant.

**Comment by x-fran** [comment]
```
	'view_manager' => [
		'template_path_stack' => [
			__DIR__ . '/../view',
		],
	],
```

all the other views are working

**Comment by acelaya** [comment]
If that's your config, the paths you tried don't seem to be correct (unless you have a nested view folder inside your view folder, haha).

Try with something like `module/mail/template`

**Comment by x-fran** [comment]
I'm so so sorry. Was my bad. Missing template_map in my module.
Now it's working. 
Thank you anyway for your support.

**Comment by acelaya** [comment]
No problem. I'm happy it's working now :)
