### ISSUE TITLE
Provide context socket via configuration

### ISSUE THREAD

**Issue by shishi666** [acelaya/ZF-AcMailer#236]
Hello,
I'm trying to use this component to send my mails, I'm using PHP version 7.3.9, the latest version of this component and I would like to know how I can configure 'mail_services' so that it works on my pc locally (without protocol https)
For the moment I have this configuration:
```php
'acmailer_options' => [
        'mail_services' => [
            'default' => [
                'transport' => 'smtp',
                'transport_options' => [
                    'host' => 'smtp.gmail.com',
                    'port' => 587,
                    'connection_class' => 'login',
                    'connection_config' => [
                        'ssl' => 'tls',
                        'username' => 'xxxx@gmail.com',
                        'password' => 'password',
                    ]
                ]
            ]
        ]
        'emails' => [
            'contact-admin' => [
                'subject' => 'Contact',
                'template' => 'mails :: contact',
            ]
        ]
    ]
```

and I get the following error:
stream_socket_enable_crypto (): SSL operation failed with code 1. Error messages: error: 1416F086: SSL routines: tls_process_server_certificate: certificate verify failed (0)

looking for it a little bit, I managed to make it work by modifying the AbstractProtocol class of the zend mail component on line 214
by adding these lines of codes:
```Php
$ socket_options = array ('ssl' => array ('verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true));
$ socket_context = stream_context_create ($ socket_options);
$ this-> socket = @stream_socket_client ($ remote, $ errorNum, $ errorStr, self :: TIMEOUT_CONNECTION, STREAM_CLIENT_CONNECT, $ socket_context);
```

I would have liked to know if it was possible to provide the context via the configuration?

thanks in advance
Shishi

**Comment by acelaya** [comment]
I'm afraid there's no way to make this module affect any internal third party code, regardless the fact that there's a configuration for it.

For me, this looks like an issue on your local env. Probably something wrong with the libopenssl or the PHP openssl extension.

I would look into that.

**Comment by acelaya** [comment]
I'm closing this for now. Let me know if there's any other way I can help.
